# Generated by Django 4.2.1 on 2023-05-15 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0005_alter_image_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["position"]},
        ),
    ]
