# Generated by Django 4.2.1 on 2023-05-21 19:48

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0009_alter_place_description_short"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="description_long",
            field=tinymce.models.HTMLField(blank=True, verbose_name="Full description"),
        ),
        migrations.AlterField(
            model_name="place",
            name="description_short",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
    ]
